[package]
name = "escrow_fresh"
version = "1.0.0"

[dependencies]
AptosFramework = { local = "../aptos-core/aptos-move/framework/aptos-framework" }

[addresses]
escrow = "4821c48de763368f2e7aeef5cfe101c9215289401eef61eb0ae5e5c38f9f3034"
